name: investors
description: Investors Portal

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  http: ^0.11.3+16
  simple_autocomplete_formfield: ^0.1.2
  transparent_image: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/
