name: privateinvestorsmobile
description: A mobile client for the ImmoScout24 private investors portal
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  easy_localization: ^2.3.2
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.4.0
  webview_flutter: ^0.3.22+1
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  auto_size_text: ^2.1.0
  flutter_switch: ^0.0.2
  provider:
  flutter_screenutil: ^1.1.0
  intl:
  geolocator: ^5.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/fonts/
    - assets/icons/
    - assets/highlights/
    - assets/images/
    - assets/objects/
    - assets/translations/

  fonts:
    - family: MakeItSans
      fonts:
        - asset: assets/fonts/MakeItSans-Bold.otf
        - asset: assets/fonts/MakeItSans-Regular.otf

    - family: ProductIconsIS
      fonts:
        - asset: assets/icons/ProductIconsIS.ttf

    - family: SystemIconsIS
      fonts:
        - asset: assets/icons/SystemIconsIS.ttf

    - family: AditionalIconsIS
      fonts:
        - asset: assets/icons/AditionalIconsIS.ttf
