name: privateinvestorsmobile
description: A mobile client for the ImmoScout24 private investors portal

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/fonts/
    - assets/icons/
    - assets/highlights/
    - assets/images/
    - assets/objects/
    - assets/images/immoscout_logo.png
    - assets/images/ftor_gerade_gradient.jpg
    - assets/images/heart@3x.png
    - assets/images/search@3x.png
    - assets/images/settings@3x.png


  fonts:
    - family: MakeItSans
      fonts:
        - asset: assets/fonts/MakeItSans-Bold.otf
        - asset: assets/fonts/MakeItSans-Regular.otf

    - family: ProductIconsIS
      fonts:
        - asset: assets/icons/ProductIconsIS.ttf

    - family:  SystemIconsIS
      fonts:
        - asset: assets/icons/SystemIconsIS.ttf

    - family: AditionalIconsIS
      fonts:
        - asset: assets/icons/AditionalIconsIS.ttf