name: privateinvestorsmobile
description: A mobile client for the ImmoScout24 private investors portal
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  auto_size_text: ^2.1.0
  flutter_switch: ^0.0.2
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/fonts/
    - assets/icons/
    - assets/highlights/
    - assets/images/
    - assets/objects/
    - assets/images/immoscout_logo.png
    - assets/images/ftor_gerade_gradient.jpg
    - assets/images/heart@3x.png
    - assets/images/search@3x.png
    - assets/images/settings@3x.png

  fonts:
    - family: MakeItSans
      fonts:
        - asset: assets/fonts/MakeItSans-Bold.otf
        - asset: assets/fonts/MakeItSans-Regular.otf

    - family: ProductIconsIS
      fonts:
        - asset: assets/icons/ProductIconsIS.ttf

    - family: SystemIconsIS
      fonts:
        - asset: assets/icons/SystemIconsIS.ttf

    - family: AditionalIconsIS
      fonts:
        - asset: assets/icons/AditionalIconsIS.ttf
