/// Flutter icons ProductIconsIS
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProductIconsIS
///      fonts:
///       - asset: fonts/ProductIconsIS.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ProductIconsIS {
  ProductIconsIS._();

  static const _kFontFam = 'ProductIconsIS';
  static const _kFontPkg = null;

  static const IconData is24_product_48px_apartment_option_2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_apartment_option = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_application_documents = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_bakeries = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_balcony = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_bicycle_as24 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_book_with_euro_sign = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_booklet_folder = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_apartment = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_assembled_house = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_bungalow = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_new_apartment_building = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_new_building = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_prefab_house = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_semi_detached_house = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_single_family_house = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_solid_construction = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_building_two_family_house = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_business = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_calculator = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_car_as24 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_car_park = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_city_district = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_doctors = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_documents_with_plus_symbol = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_elevator = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_financing_option = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_financing = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_find_location = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_fitted_kitchen = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_garden = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_geo_location = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_grocery = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_home_dwelling = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_attic = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_basement = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_ground_floor = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_loft_option = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_loft = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_maisonette = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_with_euro_sign = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_with_loupe = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_house_with_percent_icon = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_household_size = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_immo_ad = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_immo_rating = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_internet = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_key = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_kindergarden_day_care = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_land_plot_house_build = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_legal_advice = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_list_view_compare = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_location = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_map = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_mobile_communication = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_move_in = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_move_out = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_moving_planner = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_moving = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_noise_level_option = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_noise_level = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_number_of_rooms = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_occupancy = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_owner_plus = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_pedestrian_as24 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_person_with_a_checkmark = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_poll_survey = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_price_map = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_price_per_squaremeter = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_property_developer = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_property = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_public_transport_option = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_public_transport = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_radius_search = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_scale_icon = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_schools = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_smiley_icon_favorite = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_smiley_icon_maybe = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_smiley_icon_uninteresting = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_solar_potential = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_statistic_with_arrow_up = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_statistics_2_0 = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_statistics = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_taxi = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_travel_time = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_turnkey_ready_to_use = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_product_48px_wheelmap = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}