/// Flutter icons AditionalIconsIS
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AditionalIconsIS
///      fonts:
///       - asset: fonts/AditionalIconsIS.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AditionalIconsIS {
  AditionalIconsIS._();

  static const _kFontFam = 'AditionalIconsIS';
  static const _kFontPkg = null;

  static const IconData additional_icons_48px_apartment_house = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_armchair = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_ballpoint_pen = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_book = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_booklet = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_bulls_eye = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_calendar_checkmark = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_calendar_cross = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_calendar = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_camera_option = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_camera = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_chat = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_commode = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_construction_helmet = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_contrast = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_distance = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_cup = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_document_empty = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_downsize = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_enlarge = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_entrance = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_envelope = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_forbidden = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_ground_floor = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_home = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_house = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_id = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_link = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_living_space_option = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_location_pin_option = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_minus = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_monitor = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_multiple_replies = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_navigation = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_new_apartment_building_option = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_notebook = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_paperclip = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_paperplane = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_percent = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_picture = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_plus = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_price_check = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_quote_close = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_quote_open = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_reply = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_roadwork = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_room_size = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_shopping_basket = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_smiley_happy = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_smiley_neutral = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_smiley_sad = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_sort = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_sos = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_stopwatch = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_terrace_house = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_text_aligned_left_2 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_text_aligned_left = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_text = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_umbrella = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additional_icons_48px_warning = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
