/// Flutter icons SystemIconsIS
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SystemIconsIS
///      fonts:
///       - asset: fonts/SystemIconsIS.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SystemIconsIS {
  SystemIconsIS._();

  static const _kFontFam = 'SystemIconsIS';
  static const _kFontPkg = null;

  static const IconData is24_system_48px_accept = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_answer = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_appointments_move_in_day = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_archive = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_arrow_down = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_arrow_left = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_arrow_right = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_arrow_up = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_attach = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_calendar_check = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_calendar_x = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_calendar = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_cancel = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_caution = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_chevron_down = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_chevron_left = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_chevron_right = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_chevron_up = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_closing = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_collective_response = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_dashboard = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_deactivate = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_delete = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_download = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_draft = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_edit = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_email = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_error = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_favorite_like_your_property = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_heart_favorite = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_highlight_ad = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_info = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_lock_unlock = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_lock = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_menu_burger_menu = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_menu_sub_menu = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_message_read = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_message_sent = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_message_unread = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_message_unsent = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_message_write = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_message = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_move_ad_up = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_notification_alert = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_password_hide = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_password_show = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_payment_cash = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_payment_credit_card = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_payment_invoice = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_persons = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_positive_check = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_printer = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_profile = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_questionmark = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_rating_state_1 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_rating_state_2 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_rating_state_3 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_rearrange = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_remove = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_save_search_option = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_rearrange_option = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_save_search = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_search = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_settings = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_share = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_spam = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_telephone_option = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_telephone = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_upgrade_ad = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_upload = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData is24_system_48px_warning = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
